locale: "de"

backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "/public/media"
public_folder: "/public/media"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "packages/website/src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Published", name: "published", widget: "boolean" }
      - { label: "Color", name: "color", widget: "color", enableAlpha: true }
      - { label: "Place", name: "place", widget: "map", hint: "Set a location" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image(s)", name: "thumbnail", widget: "image" }
      - { label: "Rating", name: "rating", widget: "number", min: 1, max: 5 }
      - { label: "Code", name: "code", widget: "code", output_code_only: true }
      - { label: "Body", name: "body", widget: "markdown" }
